### ISSUE TITLE
PDSplitter broken ?

### ISSUE THREAD

**Issue by EasyME** [panoramicdata/PanoramicData.Blazor#10]
can't seem to get splitter to work and the [demo site](https://panoramicdata.github.io/PanoramicData.Blazor/pdsplitter) also showing it as no longer presenting splitter bars.

issue - splitter bars not present for resizing.

**Comment by MarkGoldring** [comment]
Have checked and is working in Chrome, FF and Edge.

**Comment by EasyME** [comment]
Thanks for checking, but the demo site is still not working for me.. Edge or chrome.
the splitter bar is not showing..

![Splitter_Issue_Chrome_Capture](https://user-images.githubusercontent.com/7246894/98738579-ec726d80-2375-11eb-8508-e45147ab3f3b.PNG)

**Comment by EasyME** [comment]
Update - I was able to build a test page locally.. seems the library is missing jsplit,js (needed to download and reference it on _Host.cshtml) and with that i'm able to see the splitter cursor changing once I move the mouse over to where the splitter bar is supposed to be , but the splitter bar is still not showing then locally I changed the color of gutter and there.. the splitter bar locally is showing.. but demo-site page doesn't have the bar.. perhaps I may suggest changing the gutter to a darker color ?

 .gutter {
        background-color :brown;
    }

**Comment by MarkGoldring** [comment]
Yes it wasn't clear that there was a dependency on the split.js library. I have added a small sub title to each page that details additional client side libraries required.  I have also since added tabs at the top of each demo page that allow you to view all the source files.
