### ISSUE TITLE
Demo Page: PDFileExplorer: Renaming a file crashes the demo

### ISSUE THREAD

**Issue by davidnmbond** [panoramicdata/PanoramicData.Blazor#15]
### Repro steps:
1. Click the add new file button.
2. Click-pause-click to edit
3. Type sdfsdf
4. Press return

### Expected result:
Rename works

### Actual result
Crash

**Comment by MarkGoldring** [comment]
Confirmed is an issue on WebAssembly only and not Server Side. Investigating further.

**Comment by MarkGoldring** [comment]
Fixed in library 1.0.61 onwards - was tricky little discrepancy not seen in Server Size Blazor.
