### ISSUE TITLE
PDLinkButton uses incorrect Bootstrap class of pr-3. Should be pe-xxx (pr-xxx was removed from Bootstrap)

### ISSUE THREAD

**Issue by rolandbanks** [panoramicdata/PanoramicData.Blazor#22]
Also, pr-3 is too wide (1rem).
Normal PDButtons use pr-1 (0.25rem) which is much better.

There are possibly others (not looked yet):

pl-xxx should now be ps-xxx
ml-xxx should now be ms-xxx
mr-xxx should now be me-xxx

ALSO AFFECTS the Page size label dropdown (no space to the right, as it's using pr-2, incorrectly as that class does not exist now in Bootstrap).

etc.

**Comment by MarkGoldring** [comment]
Have modified all to use newer BS5 classes, will be available in next build (2.1.43+)
