### ISSUE TITLE
PDTable: non-sortable table headers are not properly vertically aligned with sortable ones

### ISSUE THREAD

**Issue by rolandbanks** [panoramicdata/PanoramicData.Blazor#23]
Non-sortable table column headers are not middle-aligned to the same height as sortable ones. i.e. they appear lower down in the cell. If adding middle alignment (e.g. with a align-middle class on the ThClass property), they are still not quite aligned properly, due to the 'fa-stack' fixed size of 2em on the sorting element UI part.

**Comment by MarkGoldring** [comment]
Fixed with next build (2.1.43+)
