### ISSUE TITLE
Demo Page: About link goes to the wrong place

### ISSUE THREAD

**Issue by davidnmbond** [panoramicdata/PanoramicData.Blazor#3]
I'm not sure what it should do (of if it should even be there), but it currently goes to [https://docs.microsoft.com/en-gb/aspnet/core/?view=aspnetcore-3.1](https://docs.microsoft.com/en-gb/aspnet/core/?view=aspnetcore-3.1)

**Comment by MarkGoldring** [comment]
Have removed link
