### ISSUE TITLE
Demo Page: Code examples

### ISSUE THREAD

**Issue by davidnmbond** [panoramicdata/PanoramicData.Blazor#4]
Each component page should have example code showing how to use the component.

**Comment by MarkGoldring** [comment]
Have added an example / prototype on the PDBlockOverlay page, styling needs to be improved - maybe by use of CodeMirror?

**Comment by MarkGoldring** [comment]
Couldn't access source code directly as is compiled and removed at build time, however do next best thing and grab from GitHub

**Comment by MarkGoldring** [comment]
Have now added initial source code view to (and tidied up) all demo pages
